[package]
name = "wasi-vfs-cli"
version = "0.4.0"
edition = "2021"

[[bin]]
name = "wasi-vfs"

[dependencies]
anyhow = "1.0.40"
structopt = "0.3.21"
wasm-encoder = "0.38.1"
wasmparser = "0.106.0"
wizer = { git = "https://github.com/bytecodealliance/wizer.git", rev = "v3.0.1" }
